import ASAList from "@components/ASAList";
import Header from "@components/Header";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient();

const Home: NextPage = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <div data-testid="home" className={styles.container}>
        <Head>
          <title>ASAlytics</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Header />
          <ASAList />
        </main>
      </div>
    </QueryClientProvider>
  );
};

export default Home;
